export const dataMoke = [
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    }
]