export const dataMoke = [
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10005"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10006"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10007"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10008"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10009"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10010"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10011"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10012"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10013"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10014"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10015"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10016"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10017"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10018"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10019"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10020"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10021"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10022"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10023"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10024"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10025"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10026"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10027"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10028"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10029"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10030"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10031"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10032"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10033"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10034"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10035"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10036"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10037"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10040"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10041"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10042"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10043"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10044"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10045"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10047"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10048"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10049"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10050"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10051"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10052"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10053"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10054"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10055"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10056"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10057"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10058"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10059"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10058"
    },
    {
        firstname: 'Alpha', 
        name: 'mooujot', 
        startdate: '01/01/2001', 
        department: 'marketing', 
        birthdate: '02/02/1980', 
        street: '5th', 
        city: "Springfield", 
        state: "Washington", 
        zip: "10059"
    }
]